### ISSUE TITLE
the question about bunny_0_2.zip

### ISSUE THREAD

**Issue by eternal-heart** [Jhonve/GCN-Denoiser#1]
Hello,I download this code,but i can't unzip bunny_0_2.zip.I try to unzip it in windows and linux,both of them export an error "End-of-central-directory signature not found.  Either this file is not a zipfile, or it constitutes one disk of a multi-part archive.  In the latter case the central directory and zipfile comment will be found on the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of bunny_0_2.zip or bunny_0_2.zip, and cannot find bunny_0_2.zip.ZIP, period."
How can i do with this error?

**Comment by Yyanming** [comment]
hello i can not unzip bunny_0_2.zip  error . Error is same.How can i solve this question?
