### ISSUE TITLE
Setting up build project

### ISSUE THREAD

**Issue by Ruubje** [Jhonve/GCN-Denoiser#11]
Dear Jhonve,
I've found out how to setup the demo with all dependencies. Adding the DLL files from another commit didn't really work for me, but setting up all old versions of CUDA, Torch and Qt made it work. In the other issue, you also mention that building a vs project requires creating a Qt project, adding your source files and configuring the dependencies, but I'm a little stuck on the last part. How do I configure all the dependencies, such that the project is able to build? I was able to collect all third party dependencies, but I was unable to tell the project to use them. Do you have a suggestion on how to set this up effectively?
Best regards,
Ruben Band

**Comment by Jhonve** [comment]
The reason for building a new project from empty is I was using VS2017 and qt5, and I always find there are lots of problems when using a different version of IDEs.
Please install Qt and the qt extension for VS first. Then you have to create a new qt widget project (which will help you automatically create ui_xxx.h when you have an interface).
My suggestion for adding 3rd party dependencies to your project is editing your '.vcproj' files.
