### ISSUE TITLE
Testing on Ubuntu

### ISSUE THREAD

**Issue by weijiawang96** [Jhonve/GCN-Denoiser#6]
Dear Authors,

Is it easy to test the trained networks using my own shapes on Ubuntu 16.04? I only have noisy PLY mesh files (and corresponding ground truth meshes), but I'm not sure how to turn PLYs to patches. I don't know how to use `PatchData* patch_data = new PatchData(m_noised_tri_mesh, m_all_face_neighbor, m_face_area, m_face_centroid, f_it, m_flann_kd_tree, gt_normal, p_num_ring, p_radius_region);`. Since I see you read .mat files using scipy.io, is there a python approach to load PLY to your network model? I'm not doing training, I want to do testing only.

Thanks very much

**Comment by Jhonve** [comment]
We choose to use cpp with OpenMP for parallel processing. Using python for data generation takes time.
Please refer to our cpp project for more information about patch data generation.
