### ISSUE TITLE
RuntimeError: 0D or 1D target tensor expected, multi-target not supported

### ISSUE THREAD

**Issue by wei-hub** [Jhonve/GCN-Denoiser#8]
Hello, I'd like to ask, when i run the  "Python test.Py". How can I resolve this problem:
Loading pre-trained model:  ./checkpoints/23_model.t7
Load  ./checkpoints/23_model.t7  Success!
Respilt Data Success!
Traceback (most recent call last):
  File "test.py", line 77, in <module>
    test()
  File "test.py", line 64, in test
    cos_loss = F.cosine_embedding_loss(output, gt_norm, cos_target)
  File "/home/lzw/anaconda3/envs/realvsr/lib/python3.7/site-packages/torch/nn/functional.py", line 3460, in cosine_embedding_loss
    return torch.cosine_embedding_loss(input1, input2, target, margin, reduction_enum)
RuntimeError: 0D or 1D target tensor expected, multi-target not supported

**Comment by Jhonve** [comment]
This might be a torch version error. Please check your pytorch version and pytorch documentation.
